services:
  ensembled:
    build:
      context: .
      args:
        VERSION: ${VERSION:-dev}
    image: ensembled:${VERSION:-latest}
    container_name: ensembled
    volumes:
      - ./uploads:/data/uploads
    environment:
      - UPLOAD_FOLDER=/data/uploads
    stdin_open: true
    tty: true
    restart: unless-stopped