// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: ensemble.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Parameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // numeric, string, boolean, constant
	MinValue      float32                `protobuf:"fixed32,3,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`
	MaxValue      float32                `protobuf:"fixed32,4,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	Step          float32                `protobuf:"fixed32,5,opt,name=step,proto3" json:"step,omitempty"`
	Structure     string                 `protobuf:"bytes,6,opt,name=structure,proto3" json:"structure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	mi := &file_ensemble_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{0}
}

func (x *Parameter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Parameter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Parameter) GetMinValue() float32 {
	if x != nil {
		return x.MinValue
	}
	return 0
}

func (x *Parameter) GetMaxValue() float32 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

func (x *Parameter) GetStep() float32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *Parameter) GetStructure() string {
	if x != nil {
		return x.Structure
	}
	return ""
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	JobId         uint64                 `protobuf:"varint,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Values        map[string]string      `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_ensemble_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{1}
}

func (x *Job) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Job) GetJobId() uint64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *Job) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type JobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Capacity      uint32                 `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_ensemble_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{2}
}

func (x *JobRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *JobRequest) GetCapacity() uint32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

var File_ensemble_proto protoreflect.FileDescriptor

const file_ensemble_proto_rawDesc = "" +
	"\n" +
	"\x0eensemble.proto\x12\vensemble.v1\"\x9b\x01\n" +
	"\tParameter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1b\n" +
	"\tmin_value\x18\x03 \x01(\x02R\bminValue\x12\x1b\n" +
	"\tmax_value\x18\x04 \x01(\x02R\bmaxValue\x12\x12\n" +
	"\x04step\x18\x05 \x01(\x02R\x04step\x12\x1c\n" +
	"\tstructure\x18\x06 \x01(\tR\tstructure\"\xac\x01\n" +
	"\x03Job\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\x04R\x05jobId\x124\n" +
	"\x06values\x18\x03 \x03(\v2\x1c.ensemble.v1.Job.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\n" +
	"JobRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\rR\bcapacityB\x11Z\x0fpkg/ensemble/v1b\x06proto3"

var (
	file_ensemble_proto_rawDescOnce sync.Once
	file_ensemble_proto_rawDescData []byte
)

func file_ensemble_proto_rawDescGZIP() []byte {
	file_ensemble_proto_rawDescOnce.Do(func() {
		file_ensemble_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ensemble_proto_rawDesc), len(file_ensemble_proto_rawDesc)))
	})
	return file_ensemble_proto_rawDescData
}

var file_ensemble_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ensemble_proto_goTypes = []any{
	(*Parameter)(nil),  // 0: ensemble.v1.Parameter
	(*Job)(nil),        // 1: ensemble.v1.Job
	(*JobRequest)(nil), // 2: ensemble.v1.JobRequest
	nil,                // 3: ensemble.v1.Job.ValuesEntry
}
var file_ensemble_proto_depIdxs = []int32{
	3, // 0: ensemble.v1.Job.values:type_name -> ensemble.v1.Job.ValuesEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ensemble_proto_init() }
func file_ensemble_proto_init() {
	if File_ensemble_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ensemble_proto_rawDesc), len(file_ensemble_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ensemble_proto_goTypes,
		DependencyIndexes: file_ensemble_proto_depIdxs,
		MessageInfos:      file_ensemble_proto_msgTypes,
	}.Build()
	File_ensemble_proto = out.File
	file_ensemble_proto_goTypes = nil
	file_ensemble_proto_depIdxs = nil
}
